/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleestoque.view;

import br.com.controleestoque.dao.ProdutosDao;
import br.com.controleestoque.model.Produtos;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanderson M. Carvalho
 */
public class FrmControleEstoque extends javax.swing.JFrame {
    
    int idProduto, qtdNova;

    //Metodo para listar na tabela
    public void listar() throws SQLException {
        ProdutosDao dao = new ProdutosDao();
        List<Produtos> list = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) tabelaDetalhesEstoque.getModel();
        

        dados.setNumRows(0); //Apaga tudo que tem na tabela

        for (Produtos p : list) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getCodBarras(),
                p.getDescricao(),
                NumberFormat.getCurrencyInstance().format(p.getPrecoCusto()),
                NumberFormat.getCurrencyInstance().format(p.getPrecoVarejo()),
                p.getQtdEstoque(),
                p.getFornecedor().getNome()
            });
        }
    }
    
    public FrmControleEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnPesquisarProduto = new javax.swing.JButton();
        txtQtdAdicionar = new javax.swing.JTextField();
        txtEstoqueAtual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDetalhesEstoque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(126, 217, 87));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Controle de estoque de produtos");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta por data"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Estoque Atual:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Qtd:");

        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAtualizar.setText("Adicionar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descrição:");

        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyPressed(evt);
            }
        });

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisarProduto.setText("Pesquisar");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        txtQtdAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtEstoqueAtual.setEditable(false);
        txtEstoqueAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtualizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescricao)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarProduto)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarProduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizar)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstoqueAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tabelaDetalhesEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cód. de Barras", "Descrição", "Preço Atacado", "Preço Varejo", "Qtd. Estoque", "Fornecedor"
            }
        ));
        tabelaDetalhesEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDetalhesEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDetalhesEstoque);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // Botão adicionar produtos
        try {
            ProdutosDao daoProd = new ProdutosDao();
            
            int qtdEstoque, qtdParaAdicionar;
            
            qtdEstoque = Integer.parseInt(txtEstoqueAtual.getText());
            
            qtdParaAdicionar = Integer.parseInt(txtQtdAdicionar.getText());
            
            qtdNova = qtdEstoque + qtdParaAdicionar;
            
            daoProd.adicionarEstoque(idProduto, qtdNova);
            
            JOptionPane.showMessageDialog(null, "Produto atualizado");
            
            txtDescricao.setText("");
            txtEstoqueAtual.setText("");
            txtQtdAdicionar.setText("");
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Selecione o produto ou informe a quantidade " + erro);
        }
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void tabelaDetalhesEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDetalhesEstoqueMouseClicked
        //Quando clicar em uma venda
        idProduto = Integer.parseInt(tabelaDetalhesEstoque.getValueAt(tabelaDetalhesEstoque.getSelectedRow(), 0).toString());
        
        txtDescricao.setText(tabelaDetalhesEstoque.getValueAt(tabelaDetalhesEstoque.getSelectedRow(), 2).toString());
        txtEstoqueAtual.setText(tabelaDetalhesEstoque.getValueAt(tabelaDetalhesEstoque.getSelectedRow(), 5).toString());
        
    }//GEN-LAST:event_tabelaDetalhesEstoqueMouseClicked

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
       try {
            //Butão pesquisar
            String nome = "%" + txtDescricao.getText() + "%";
            
            ProdutosDao dao = new ProdutosDao();
            List<Produtos> list = dao.listarProdutosPorNome(nome);
            
            DefaultTableModel dados = (DefaultTableModel) tabelaDetalhesEstoque.getModel();
            
            dados.setNumRows(0); //Apaga tudo que tem na tabela
            
            for (Produtos p : list) {
                dados.addRow(new Object[]{
                    p.getId(),
                    p.getCodBarras(),
                    p.getDescricao(),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoCusto()),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoVarejo()),
                    p.getQtdEstoque(),
                    p.getFornecedor().getNome()
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro);
        }
       
    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            // Lista produtos na tabela da tela controle de estoque
            listar();
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro);
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyPressed
        // Pesquisa no momento em que o usuario vai digitando
        try {
            String nome = "%" + txtDescricao.getText() + "%";
            
            ProdutosDao dao = new ProdutosDao();
            List<Produtos> list = dao.listarProdutosPorNome(nome);
            
            DefaultTableModel dados = (DefaultTableModel) tabelaDetalhesEstoque.getModel();
            
            dados.setNumRows(0); //Apaga tudo que tem na tabela
            
            for (Produtos p : list) {
                dados.addRow(new Object[]{
                    p.getId(),
                    p.getCodBarras(),
                    p.getDescricao(),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoCusto()),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoVarejo()),
                    p.getQtdEstoque(),
                    p.getFornecedor().getNome()
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro);
        }
        
        //Pesquisa com um ENTER
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
            String nome = "%" + txtDescricao.getText() + "%";
            
            ProdutosDao dao = new ProdutosDao();
            List<Produtos> list = dao.listarProdutosPorNome(nome);
            
            DefaultTableModel dados = (DefaultTableModel) tabelaDetalhesEstoque.getModel();
            
            dados.setNumRows(0); //Apaga tudo que tem na tabela
            
            for (Produtos p : list) {
                dados.addRow(new Object[]{
                    p.getId(),
                    p.getCodBarras(),
                    p.getDescricao(),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoCusto()),
                    NumberFormat.getCurrencyInstance().format(p.getPrecoVarejo()),
                    p.getQtdEstoque(),
                    p.getFornecedor().getNome()
                });
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro);
        }
        }
    }//GEN-LAST:event_txtDescricaoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmControleEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmControleEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDetalhesEstoque;
    private javax.swing.JTextField txtDescricao;
    public javax.swing.JTextField txtEstoqueAtual;
    private javax.swing.JTextField txtQtdAdicionar;
    // End of variables declaration//GEN-END:variables
}
