/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.controleestoque.view;

import java.awt.event.KeyEvent;
import java.text.NumberFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanderson M. Carvalho
 */
public class FrmDesconto extends javax.swing.JFrame {

    /**
     * Creates new form FrmTotalVenda
     */
    FrmVendas telaVendas = new FrmVendas();

    int linha;
    double desconto, valorDesconto, descontoConcedido, subtotal, subtotalAtulizado;

    public FrmDesconto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnCederDesconto = new javax.swing.JButton();
        txtDesconto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSenhaDesconto = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnCederDesconto1 = new javax.swing.JButton();
        txtSenhaCancelar = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Desconto/Cancelamento");

        jPanel1.setBackground(new java.awt.Color(126, 217, 87));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desconto/Cancelamento");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Conceder Desconto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Informe a % de desconto:");

        btnCederDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCederDesconto.setText("OK");
        btnCederDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCederDescontoActionPerformed(evt);
            }
        });

        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescontoKeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Senha:");

        txtSenhaDesconto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSenhaDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaDescontoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtSenhaDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnCederDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCederDesconto)
                    .addComponent(jLabel10)
                    .addComponent(txtSenhaDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cancelar Lançamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Senha:");

        btnCederDesconto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCederDesconto1.setText("Cancelar");
        btnCederDesconto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCederDesconto1ActionPerformed(evt);
            }
        });

        txtSenhaCancelar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtSenhaCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSenhaCancelarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtSenhaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnCederDesconto1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnCederDesconto1)
                    .addComponent(txtSenhaCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCederDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCederDescontoActionPerformed
        // Botão que calcula o totalComDesconto de vendas por data
        if ("123".equals(txtSenhaDesconto.getText())) {

            desconto = Double.parseDouble(txtDesconto.getText());

            if (desconto >= 2) {
                if (desconto <= 20) {
                    descontoConcedido = desconto / 100;

                    valorDesconto = subtotal * descontoConcedido; //Calcula o valor a ser retirado do sbtotal

                    subtotalAtulizado = subtotal - valorDesconto;

                    concederDesconto();

                    JOptionPane.showMessageDialog(null, "Desconto concedido.");

                    this.dispose();

                } else {

                    JOptionPane.showMessageDialog(null, "O desconto informado deve está no intervalo entre 2 à 20%");

                }

            } else {

                JOptionPane.showMessageDialog(null, "O desconto informado deve está no intervalo entre 2 à 20%");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta.");
        }
    }//GEN-LAST:event_btnCederDescontoActionPerformed

    private void btnCederDesconto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCederDesconto1ActionPerformed
        // Botão cancelar venda
        if ("123".equals(txtSenhaCancelar.getText())) {

            DefaultTableModel modelItens = (DefaultTableModel) telaVendas.tabelaItens.getModel();

            if ((modelItens.getValueAt(linha, 4)) != null) {
                valorDesconto = Double.parseDouble(modelItens.getValueAt(linha, 4).toString().
                        substring(3, modelItens.getValueAt(linha, 4).toString().length()).replaceAll(",", "."));
            } else {
                valorDesconto = 0;
            }

            cancelarVenda();

            JOptionPane.showMessageDialog(null, "Lançamento cancelado.");

            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Senha incorreta.");
        }
    }//GEN-LAST:event_btnCederDesconto1ActionPerformed

    private void txtSenhaDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaDescontoKeyPressed
        // Quando apertar o botão enter em senha/desconto
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("123".equals(txtSenhaDesconto.getText())) {

                desconto = Double.parseDouble(txtDesconto.getText());

                if (desconto >= 2) {
                    if (desconto <= 20) {
                        descontoConcedido = desconto / 100;

                        valorDesconto = subtotal * descontoConcedido; //Calcula o valor a ser retirado do sbtotal

                        subtotalAtulizado = subtotal - valorDesconto;

                        concederDesconto();

                        JOptionPane.showMessageDialog(null, "Desconto concedido.");

                        this.dispose();

                    } else {

                        JOptionPane.showMessageDialog(null, "O desconto informado deve está no intervalo entre 2 à 20%");

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "O desconto informado deve está no intervalo entre 2 à 20%");

                }

            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta.");
            }
        }
    }//GEN-LAST:event_txtSenhaDescontoKeyPressed

    private void txtSenhaCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaCancelarKeyPressed
        // Quando apertar o botão enter em senha/cancelar
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if ("123".equals(txtSenhaCancelar.getText())) {

                DefaultTableModel modelItens = (DefaultTableModel) telaVendas.tabelaItens.getModel();

                if ((modelItens.getValueAt(linha, 4)) != null) {
                    valorDesconto = Double.parseDouble(modelItens.getValueAt(linha, 4).toString().
                            substring(3, modelItens.getValueAt(linha, 4).toString().length()).replaceAll(",", "."));
                } else {
                    valorDesconto = 0;
                }

                cancelarVenda();

                JOptionPane.showMessageDialog(null, "Lançamento cancelado.");

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Senha incorreta.");
            }
        }

    }//GEN-LAST:event_txtSenhaCancelarKeyPressed

    private void txtDescontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescontoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescontoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDesconto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDesconto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCederDesconto;
    private javax.swing.JButton btnCederDesconto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JPasswordField txtSenhaCancelar;
    private javax.swing.JPasswordField txtSenhaDesconto;
    // End of variables declaration//GEN-END:variables

    private void concederDesconto() {
        telaVendas.tabelaItens.setValueAt(NumberFormat.getCurrencyInstance().format(valorDesconto), linha, 4);
        telaVendas.tabelaItens.setValueAt(NumberFormat.getCurrencyInstance().format(subtotalAtulizado), linha, 5);
        telaVendas.totalComDesconto -= valorDesconto;
        telaVendas.desconto += valorDesconto;
        telaVendas.txtTotalGeral.setText(String.valueOf(NumberFormat.getCurrencyInstance().format(telaVendas.totalComDesconto)));
        telaVendas.txtTotalDesconto.setText(String.valueOf(NumberFormat.getCurrencyInstance().format(telaVendas.desconto)));
    }

    private void cancelarVenda() {
        DefaultTableModel model = (DefaultTableModel) telaVendas.tabelaItens.getModel();
        model.removeRow(linha);

        telaVendas.totalComDesconto -= subtotal;
        telaVendas.desconto -= valorDesconto;
        telaVendas.txtTotalGeral.setText(String.valueOf(NumberFormat.getCurrencyInstance().format(telaVendas.totalComDesconto)));
        telaVendas.txtTotalDesconto.setText(String.valueOf(NumberFormat.getCurrencyInstance().format(telaVendas.desconto)));
        telaVendas.tabelaItens.updateUI();
    }
}
